---

- name: Setting wildfly_home fact for further reference 
  set_fact:
    wildfly_home: /opt/wildfly-11.0.0.CR1
    
- name: Register wildfly_home
  stat: 
    path: /opt/wildfly-11.0.0.CR1
  register: wildfly_folder

- name: Ensure that wildfly group is present
  group:
    name: wildfly

- name: Ensure that wildfly user is present
  user:
    name: wildfly
    group: wildfly

- name: Download and unarchive wildfly distribution
  unarchive:
    src: http://download.jboss.org/wildfly/11.0.0.CR1/wildfly-11.0.0.CR1.tar.gz
    dest: /opt
    group: wildfly
    owner: wildfly
    remote_src: yes
  when: not wildfly_folder.stat.exists
    