---

- name: Add service script for systemd
  template:
    src: wildfly.service.j2
    dest: /etc/systemd/system/wildfly.service
   
- name: Register service using systemd
  systemd: 
    state: started 
    enabled: yes
    name: wildfly.service
    daemon_reload: yes    